sudo: false

language: ruby
rvm:
  - 2.0.0-p247

before_script:
  - npm install -g grunt-cli bower
  - bower install
  - npm install
  - bundle install

script: grunt

after_success:
  - grunt deploy
