# Jekyll configuration precedence:
# 1. Gruntfile task
# 2. config.build.yml
# 3. config.yml

name: Grncom Solutions
description: Providing quality and reliable computing solutions
title: Providing quality and reliable computing solutions
author:
  name: kerrongordon
  email: kgpsounds.com@gmail.com

facebook: GrncomSolutions
googlePlus: Grncomsolutions
twitter: grncomsolutions

# Grunt handles images and assets.
exclude: ['img', 'css', 'js', 'fonts',
          '**.png', '**.jpg', '**.jpeg', '**.gif', '**.webp', '**.svg', '**.ico', 'vendor']

include: ['.htaccess', 'favicon.png']

# _config.build.yml sets future and show_drafts to false on `grunt build`
future: true
show_drafts: true
baseurl: ''  #/gsetri-website

# Markdown library
markdown: redcarpet
#   extensions: ['fenced_code_blocks', 'smart']

highlighter: true
